service: favip-test
provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 512
  timeout: 15
  logRetentionInDays: 90
  logs:
    httpApi: true
  httpApi:
    # metrics: true # Enable if you need
    cors: true

custom:
  stage: ${opt:stage, 'offline'}
  region: ${opt:region, 'us-east-1'}
  serverless-offline:
    httpPort: 8000
    noPrependStageInUrl: true
    reloadHandler: true

functions:
  app:
    handler: src/handler.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}

package:
  patterns:
    - "!**/*.test.ts"
  individually: true

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
