version: "3.9"
services:
  nginx:
    image: nginx:1.21.3-alpine
    container_name: nginx
    extra_hosts:
      - "dockerhost:54.233.81.73"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./config:/etc/nginx/conf.d/config:ro
    restart: on-failure
